dist: xenial
language: python
services:
  - xvfb
python:
  - "3.6"
  - "3.7"
  - "3.8" 
  - "pypy"
  - "pypy3"
# - "nightly"

matrix:
  allow_failures:
    python: "nightly"

install: pip install tox-travis

# command to install dependencies
install:
  - pip install pandas
  - pip install git+https://github.com/blampe/IbPy.git
# - pip install your_package

script: tox

# command to run tests
script: cd tests && nosetests -v -v
