dist: xenial
language: python
services:
  - xvfb
python:
  - "3.8"
  - "3.9"
  - "3.10"
# - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

# command to install dependencies
install:
  - pip install -r requirements-test.txt
  - pip install pandas
  - pip install git+https://github.com/blampe/IbPy.git
# - pip install your_package

script:
  - pytest
  - cd tests && nosetests -v
