import backtrader as bt
from _typeshed import Incomplete

__all__ = ['DrawDown', 'TimeDrawDown']

class DrawDown(bt.Analyzer):
    params: Incomplete
    def start(self) -> None: ...
    rets: Incomplete
    def create_analysis(self) -> None: ...
    def stop(self) -> None: ...
    def notify_fund(self, cash, value, fundvalue, shares) -> None: ...
    def next(self) -> None: ...

class TimeDrawDown(bt.TimeFrameAnalyzerBase):
    params: Incomplete
    dd: float
    maxdd: float
    maxddlen: int
    peak: Incomplete
    ddlen: int
    def start(self) -> None: ...
    def on_dt_over(self) -> None: ...
    def stop(self) -> None: ...
