from _typeshed import Incomplete
from backtrader import TimeFrameAnalyzerBase as TimeFrameAnalyzerBase

class TimeReturn(TimeFrameAnalyzerBase):
    params: Incomplete
    def start(self) -> None: ...
    def notify_fund(self, cash, value, fundvalue, shares) -> None: ...
    def on_dt_over(self) -> None: ...
    def next(self) -> None: ...
