from . import Returns as Returns
from ..mathsupport import standarddev as standarddev
from _typeshed import Incomplete
from backtrader import TimeFrameAnalyzerBase as TimeFrameAnalyzerBase

class VWR(TimeFrameAnalyzerBase):
    params: Incomplete
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def notify_fund(self, cash, value, fundvalue, shares) -> None: ...
VariabilityWeightedReturn = VWR
