import datetime
from .py3 import string_types as string_types
from _typeshed import Incomplete

ZERO: Incomplete
STDOFFSET: Incomplete
DSTOFFSET: Incomplete
DSTOFFSET = STDOFFSET
DSTDIFF: Incomplete
TIME_MAX: Incomplete
TIME_MIN: Incomplete

def tzparse(tz): ...
def Localizer(tz): ...

class _UTC(datetime.tzinfo):
    def utcoffset(self, dt): ...
    def tzname(self, dt): ...
    def dst(self, dt): ...
    def localize(self, dt): ...

class _LocalTimezone(datetime.tzinfo):
    def utcoffset(self, dt): ...
    def dst(self, dt): ...
    def tzname(self, dt): ...
    def localize(self, dt): ...

UTC: Incomplete
TZLocal: Incomplete
HOURS_PER_DAY: float
MINUTES_PER_HOUR: float
SECONDS_PER_MINUTE: float
MUSECONDS_PER_SECOND: float
MINUTES_PER_DAY: Incomplete
SECONDS_PER_DAY: Incomplete
MUSECONDS_PER_DAY: Incomplete

def num2date(x, tz: Incomplete | None = None, naive: bool = True): ...
def num2dt(num, tz: Incomplete | None = None, naive: bool = True): ...
def num2time(num, tz: Incomplete | None = None, naive: bool = True): ...
def date2num(dt, tz: Incomplete | None = None): ...
def time2num(tm): ...
