from _typeshed import Incomplete

class flushfile:
    f: Incomplete
    def __init__(self, f) -> None: ...
    def write(self, x) -> None: ...
    def flush(self) -> None: ...

class StdOutDevNull:
    stdout: Incomplete
    def __init__(self) -> None: ...
    def write(self, x) -> None: ...
    def flush(self) -> None: ...
    def stop(self) -> None: ...
