from _typeshed import Incomplete

MAXINT: Incomplete
MININT: Incomplete
MAXFLOAT: Incomplete
MINFLOAT: Incomplete
string_types: Incomplete
integer_types: Incomplete
filter = filter
map = map
range = range
zip = zip
long = int

def cmp(a, b): ...
def bytes(x): ...
def bstr(x): ...
def iterkeys(d): ...
def itervalues(d): ...
def iteritems(d): ...
def keys(d): ...
def values(d): ...
def items(d): ...
def with_metaclass(meta, *bases): ...
