import matplotlib.ticker as mplticker
from ..utils import num2date as num2date
from _typeshed import Incomplete

class MyVolFormatter(mplticker.Formatter):
    Suffixes: Incomplete
    volmax: Incomplete
    divisor: float
    suffix: Incomplete
    def __init__(self, volmax) -> None: ...
    def __call__(self, y, pos: int = 0): ...

class MyDateFormatter(mplticker.Formatter):
    dates: Incomplete
    lendates: Incomplete
    fmt: Incomplete
    def __init__(self, dates, fmt: str = '%Y-%m-%d') -> None: ...
    def __call__(self, x, pos: int = 0): ...

def patch_locator(locator, xdates): ...
def patch_formatter(formatter, xdates): ...
def getlocator(xdates, numticks: int = 5, tz: Incomplete | None = None): ...
