from _typeshed import Incomplete
from matplotlib.dates import AutoDateFormatter as ADFormatter, AutoDateLocator as ADLocator, RRuleLocator as RRLocator

class RRuleLocator(RRLocator):
    def __init__(self, dates, o, tz: Incomplete | None = None) -> None: ...
    def datalim_to_dt(self): ...
    def viewlim_to_dt(self): ...
    def tick_values(self, vmin, vmax): ...

class AutoDateLocator(ADLocator):
    def __init__(self, dates, *args, **kwargs) -> None: ...
    def datalim_to_dt(self): ...
    def viewlim_to_dt(self): ...
    def tick_values(self, vmin, vmax): ...
    def get_locator(self, dmin, dmax): ...

class AutoDateFormatter(ADFormatter):
    def __init__(self, dates, locator, tz: Incomplete | None = None, defaultfmt: str = '%Y-%m-%d') -> None: ...
    def __call__(self, x, pos: Incomplete | None = None): ...
