from .. import AutoInfoClass as AutoInfoClass, MetaParams as MetaParams, TimeFrame as TimeFrame, date2num as date2num
from ..utils.py3 import integer_types as integer_types, range as range, with_metaclass as with_metaclass
from .finance import plot_candlestick as plot_candlestick, plot_lineonclose as plot_lineonclose, plot_ohlc as plot_ohlc, plot_volume as plot_volume
from .formatters import MyDateFormatter as MyDateFormatter, MyVolFormatter as MyVolFormatter
from .multicursor import MultiCursor as MultiCursor
from .scheme import PlotScheme as PlotScheme
from .utils import tag_box_style as tag_box_style
from _typeshed import Incomplete

class PInfo:
    sch: Incomplete
    nrows: int
    row: int
    clock: Incomplete
    x: Incomplete
    xlen: int
    sharex: Incomplete
    figs: Incomplete
    cursors: Incomplete
    daxis: Incomplete
    vaxis: Incomplete
    zorder: Incomplete
    coloridx: Incomplete
    handles: Incomplete
    labels: Incomplete
    legpos: Incomplete
    prop: Incomplete
    def __init__(self, sch) -> None: ...
    def newfig(self, figid, numfig, mpyplot): ...
    def nextcolor(self, ax): ...
    def color(self, ax): ...
    def zordernext(self, ax): ...
    def zordercur(self, ax): ...

class Plot_OldSync(Incomplete):
    params: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def drawtag(self, ax, x, y, facecolor, edgecolor, alpha: float = 0.9, **kwargs) -> None: ...
    mpyplot: Incomplete
    pinf: Incomplete
    def plot(self, strategy, figid: int = 0, numfigs: int = 1, iplot: bool = True, start: Incomplete | None = None, end: Incomplete | None = None, **kwargs): ...
    def setlocators(self, ax): ...
    def calcrows(self, strategy) -> None: ...
    def newaxis(self, obj, rowspan): ...
    def plotind(self, iref, ind, subinds: Incomplete | None = None, upinds: Incomplete | None = None, downinds: Incomplete | None = None, masterax: Incomplete | None = None) -> None: ...
    def plotvolume(self, data, opens, highs, lows, closes, volumes, label): ...
    def plotdata(self, data, indicators) -> None: ...
    def show(self) -> None: ...
    def savefig(self, fig, filename, width: int = 16, height: int = 9, dpi: int = 300, tight: bool = True) -> None: ...
    dplotstop: Incomplete
    dplotsup: Incomplete
    dplotsdown: Incomplete
    dplotsover: Incomplete
    def sortdataindicators(self, strategy) -> None: ...
Plot = Plot_OldSync
