import backtrader as bt
from _typeshed import Incomplete
from backtrader.utils.py3 import range as range

class MetaChainer(bt.DataBase.__class__):
    def __init__(cls, name, bases, dct) -> None: ...
    def donew(cls, *args, **kwargs): ...

class Chainer(Incomplete):
    def islive(self): ...
    def __init__(self, *args) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_notifications(self): ...
