from _typeshed import Incomplete
from backtrader import TimeFrame as TimeFrame, date2num as date2num, num2date as num2date
from backtrader.feed import DataBase as DataBase
from backtrader.stores import ibstore as ibstore
from backtrader.utils.py3 import integer_types as integer_types, queue as queue, string_types as string_types, with_metaclass as with_metaclass

class MetaIBData(DataBase.__class__):
    def __init__(cls, name, bases, dct) -> None: ...

class IBData(Incomplete):
    params: Incomplete
    RTBAR_MINSIZE: Incomplete
    def islive(self): ...
    ib: Incomplete
    precontract: Incomplete
    pretradecontract: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def setenvironment(self, env) -> None: ...
    def parsecontract(self, dataname): ...
    qlive: Incomplete
    qhist: Incomplete
    contract: Incomplete
    contractdetails: Incomplete
    tradecontract: Incomplete
    tradecontractdetails: Incomplete
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def reqdata(self): ...
    def canceldata(self) -> None: ...
    def haslivedata(self): ...
