from _typeshed import Incomplete
from backtrader import date2num as date2num, num2date as num2date
from backtrader.feed import DataBase as DataBase
from backtrader.stores import oandastore as oandastore
from backtrader.utils.py3 import queue as queue, with_metaclass as with_metaclass

class MetaOandaData(DataBase.__class__):
    def __init__(cls, name, bases, dct) -> None: ...

class OandaData(Incomplete):
    params: Incomplete
    def islive(self): ...
    o: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def setenvironment(self, env) -> None: ...
    qlive: Incomplete
    contractdetails: Incomplete
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def haslivedata(self): ...
