import backtrader as bt
from _typeshed import Incomplete

class MetaRollOver(bt.DataBase.__class__):
    def __init__(cls, name, bases, dct) -> None: ...
    def donew(cls, *args, **kwargs): ...

class RollOver(Incomplete):
    params: Incomplete
    def islive(self): ...
    def __init__(self, *args) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
