import backtrader as bt
from _typeshed import Incomplete
from backtrader.utils.dateintern import date2num as date2num

class MetaVChartFile(bt.DataBase.__class__):
    def __init__(self, name, bases, dct) -> None: ...

class VChartFile(Incomplete):
    def __init__(self, *args, **kwargs) -> None: ...
    f: Incomplete
    def start(self) -> None: ...
    def stop(self) -> None: ...
