from _typeshed import Incomplete

class BarReplayer_Open:
    pendingbar: Incomplete
    def __init__(self, data) -> None: ...
    def __call__(self, data): ...
    def last(self, data): ...
DayStepsFilter = BarReplayer_Open
