import backtrader as bt
from _typeshed import Incomplete
from backtrader import TimeFrame as TimeFrame
from backtrader.utils.py3 import MAXINT as MAXINT, with_metaclass as with_metaclass

class MetaAnalyzer(bt.MetaParams):
    def donew(cls, *args, **kwargs): ...
    def dopostinit(cls, _obj, *args, **kwargs): ...

class Analyzer(Incomplete):
    csv: bool
    def __len__(self) -> int: ...
    def notify_cashvalue(self, cash, value) -> None: ...
    def notify_fund(self, cash, value, fundvalue, shares) -> None: ...
    def notify_order(self, order) -> None: ...
    def notify_trade(self, trade) -> None: ...
    def next(self) -> None: ...
    def prenext(self) -> None: ...
    def nextstart(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    rets: Incomplete
    def create_analysis(self) -> None: ...
    def get_analysis(self): ...
    def print(self, *args, **kwargs) -> None: ...
    def pprint(self, *args, **kwargs) -> None: ...

class MetaTimeFrameAnalyzerBase(Analyzer.__class__):
    def __new__(meta, name, bases, dct): ...

class TimeFrameAnalyzerBase(Incomplete):
    params: Incomplete
    def on_dt_over(self) -> None: ...
