from _typeshed import Incomplete
from backtrader.comminfo import CommInfoBase as CommInfoBase
from backtrader.metabase import MetaParams as MetaParams
from backtrader.utils.py3 import with_metaclass as with_metaclass

class MetaBroker(MetaParams):
    def __init__(cls, name, bases, dct) -> None: ...

class BrokerBase(Incomplete):
    params: Incomplete
    comminfo: Incomplete
    def __init__(self) -> None: ...
    def init(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def add_order_history(self, orders, notify: bool = False) -> None: ...
    def set_fund_history(self, fund) -> None: ...
    def getcommissioninfo(self, data): ...
    def setcommission(self, commission: float = 0.0, margin: Incomplete | None = None, mult: float = 1.0, commtype: Incomplete | None = None, percabs: bool = True, stocklike: bool = False, interest: float = 0.0, interest_long: bool = False, leverage: float = 1.0, automargin: bool = False, name: Incomplete | None = None) -> None: ...
    def addcommissioninfo(self, comminfo, name: Incomplete | None = None) -> None: ...
    def getcash(self) -> None: ...
    def getvalue(self, datas: Incomplete | None = None) -> None: ...
    def get_fundshares(self): ...
    fundshares: Incomplete
    def get_fundvalue(self): ...
    fundvalue: Incomplete
    def set_fundmode(self, fundmode, fundstartval: Incomplete | None = None) -> None: ...
    def get_fundmode(self): ...
    fundmode: Incomplete
    def getposition(self, data) -> None: ...
    def submit(self, order) -> None: ...
    def cancel(self, order) -> None: ...
    def buy(self, owner, data, size, price: Incomplete | None = None, plimit: Incomplete | None = None, exectype: Incomplete | None = None, valid: Incomplete | None = None, tradeid: int = 0, oco: Incomplete | None = None, trailamount: Incomplete | None = None, trailpercent: Incomplete | None = None, **kwargs) -> None: ...
    def sell(self, owner, data, size, price: Incomplete | None = None, plimit: Incomplete | None = None, exectype: Incomplete | None = None, valid: Incomplete | None = None, tradeid: int = 0, oco: Incomplete | None = None, trailamount: Incomplete | None = None, trailpercent: Incomplete | None = None, **kwargs) -> None: ...
    def next(self) -> None: ...
