from .metabase import MetaParams as MetaParams
from .utils.py3 import with_metaclass as with_metaclass
from _typeshed import Incomplete

class CommInfoBase(Incomplete):
    COMM_PERC: Incomplete
    COMM_FIXED: Incomplete
    params: Incomplete
    def __init__(self) -> None: ...
    @property
    def margin(self): ...
    @property
    def stocklike(self): ...
    def get_margin(self, price): ...
    def get_leverage(self): ...
    def getsize(self, price, cash): ...
    def getoperationcost(self, size, price): ...
    def getvaluesize(self, size, price): ...
    def getvalue(self, position, price): ...
    def getcommission(self, size, price): ...
    def confirmexec(self, size, price): ...
    def profitandloss(self, size, price, newprice): ...
    def cashadjust(self, size, price, newprice): ...
    def get_credit_interest(self, data, pos, dt): ...

class CommissionInfo(CommInfoBase):
    params: Incomplete
