from .metabase import MetaParams
from _typeshed import Incomplete

__all__ = ['Filter']

class MetaFilter(MetaParams): ...

class Filter(Incomplete):
    def __init__(self, data) -> None: ...
    def __call__(self, data) -> None: ...
    def nextstart(self, data) -> None: ...
    def next(self, data) -> None: ...
