from . import metabase as metabase
from .utils.py3 import range as range, with_metaclass as with_metaclass
from _typeshed import Incomplete

class MetaLineRoot(metabase.MetaParams):
    def donew(cls, *args, **kwargs): ...

class LineRoot(Incomplete):
    IndType: Incomplete
    StratType: Incomplete
    ObsType: Incomplete
    def qbuffer(self, savemem: int = 0) -> None: ...
    def minbuffer(self, size) -> None: ...
    def setminperiod(self, minperiod) -> None: ...
    def updateminperiod(self, minperiod) -> None: ...
    def addminperiod(self, minperiod) -> None: ...
    def incminperiod(self, minperiod) -> None: ...
    def prenext(self) -> None: ...
    def nextstart(self) -> None: ...
    def next(self) -> None: ...
    def preonce(self, start, end) -> None: ...
    def oncestart(self, start, end) -> None: ...
    def once(self, start, end) -> None: ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __div__(self, other): ...
    def __rdiv__(self, other): ...
    def __floordiv__(self, other): ...
    def __rfloordiv__(self, other): ...
    def __truediv__(self, other): ...
    def __rtruediv__(self, other): ...
    def __pow__(self, other): ...
    def __rpow__(self, other): ...
    def __abs__(self): ...
    def __neg__(self): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    __hash__: Incomplete

class LineMultiple(LineRoot):
    def reset(self) -> None: ...
    def addminperiod(self, minperiod) -> None: ...
    def incminperiod(self, minperiod) -> None: ...
    def qbuffer(self, savemem: int = 0) -> None: ...
    def minbuffer(self, size) -> None: ...

class LineSingle(LineRoot):
    def addminperiod(self, minperiod) -> None: ...
    def incminperiod(self, minperiod) -> None: ...
