from _typeshed import Incomplete

def average(x, bessel: bool = False): ...
def variance(x, avgx: Incomplete | None = None): ...
def standarddev(x, avgx: Incomplete | None = None, bessel: bool = False): ...
