from _typeshed import Incomplete

class Position:
    size: Incomplete
    price: Incomplete
    adjbase: Incomplete
    upopened: Incomplete
    upclosed: int
    updt: Incomplete
    def __init__(self, size: int = 0, price: float = 0.0) -> None: ...
    def fix(self, size, price): ...
    price_orig: Incomplete
    def set(self, size, price): ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__
    def clone(self): ...
    def pseudoupdate(self, size, price): ...
    datetime: Incomplete
    def update(self, size, price, dt: Incomplete | None = None): ...
