from _typeshed import Incomplete

__all__ = ['TradingCalendarBase', 'TradingCalendar', 'PandasMarketCalendar']

class TradingCalendarBase(Incomplete):
    def schedule(self, day) -> None: ...
    def nextday(self, day): ...
    def nextday_week(self, day) -> None: ...
    def last_weekday(self, day): ...
    def last_monthday(self, day): ...
    def last_yearday(self, day): ...

class TradingCalendar(TradingCalendarBase):
    params: Incomplete
    def __init__(self) -> None: ...
    def schedule(self, day, tz: Incomplete | None = None): ...

class PandasMarketCalendar(TradingCalendarBase):
    params: Incomplete
    dcache: Incomplete
    idcache: Incomplete
    csize: Incomplete
    def __init__(self) -> None: ...
    def schedule(self, day, tz: Incomplete | None = None): ...
