from _typeshed import Incomplete

DATAFORMATS: Incomplete
TIMEFRAMES: Incomplete

def btrun(pargs: str = '') -> None: ...
def setbroker(args, cerebro) -> None: ...
def getdatas(args): ...
def getmodclasses(mod, clstype, clsname: Incomplete | None = None): ...
def getmodfunctions(mod, funcname: Incomplete | None = None): ...
def loadmodule(modpath, modname: str = ''): ...
def loadmodule2(modpath, modname): ...
def loadmodule3(modpath, modname): ...
def getobjects(iterable, clsbase, modbase, issignal: bool = False): ...
def getfunctions(iterable, modbase): ...
def parse_args(pargs: str = ''): ...
