from . import And as And, Indicator as Indicator
from _typeshed import Incomplete

class NonZeroDifference(Indicator):
    alias: Incomplete
    lines: Incomplete
    def nextstart(self) -> None: ...
    def next(self) -> None: ...
    def oncestart(self, start, end) -> None: ...
    def once(self, start, end) -> None: ...

class _CrossBase(Indicator):
    lines: Incomplete
    plotinfo: Incomplete
    def __init__(self) -> None: ...

class CrossUp(_CrossBase): ...
class CrossDown(_CrossBase): ...

class CrossOver(Indicator):
    lines: Incomplete
    plotinfo: Incomplete
    def __init__(self) -> None: ...
